services:

#EcomApp-Containers

# Postgres Data Base

  postgres:
    container_name: postgres
    image: postgres:latest
    mem_limit: 700m
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: orderdb
      PGDATA: /data/postgres
    env_file:
      - .env
    volumes:
       - postgres:/data/postgres
       - ./init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

# PGadmin

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    mem_limit: 700m
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pgadmin:/var/lib/pgadmin
     
    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped

    #MYSQL Data Base

  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: productdb
      MYSQL_USER: productdb
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: productdb
    volumes:
        - mysql_data:/temp/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
    restart: unless-stopped

 #MYSQL WorkBench

  mysql-workbench:
    image: phpmyadmin/phpmyadmin
    container_name: mysql-workbench
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: productdb
    ports:
      - "8484:80"
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - backend

#MONGO Data Base

  mongo:
    container_name: mongo
    image: mongo
    environment:
       MONGO_INITDB_DATABASE: userdb
    volumes:
       - mongo_data:/data/db # Persist MongoDB data
       - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    networks:
      - backend
    restart: unless-stopped

# Keycloak 

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.4
    container_name: keycloak
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8096
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloakdb
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: root
    ports:
      - 8096:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - backend

# Zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend
      
# Kafka

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - backend

# Kafka UI

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8089:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092 # Internal Kafka broker address
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181 # Zookeeper address (optional for newer Kafka versions)
      KAFKA_CLUSTERS_0_JMXPORT: 9999 # Optional, if JMX is enabled on Kafka
    networks:
      - backend

# Zipkin

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
     - backend

# Redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
     - backend

# Rabbitmq

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

#EcomApp-ConfigServer

  configserver:
    build: .
    container_name: configserver
    ports:
      - 8086:8086
    networks:
     - backend


#EcomApp-EurekaServer
#EcomApp-User
#EcomApp-Order
#EcomApp-Product
#EcomApp-ApiGateway

networks:
  backend:
    driver: bridge 

volumes:
  postgres:
  pgadmin:
  mysql_data:
  mongo_data: