build:
   id: 103
   version: 1.4.3
   name: "Native Dev-Production-Build"
   type: "Native Development Build"
#spring:
# rabbitmq:
#  host: localhost
#  port: 5672
#  username: guest
#  password: guest
#
#management:
# endpoints:
#  web:
#    exposure:
#     include: "*"