#spring.application.name=eureka-server


server:
  port: 8761
  
#server:
#  port: 8091

eureka:
 client:
  register-with-eureka: false
  fetch-registry: false

management:
   endpoints:
     web:
      exposure:
       include: "*" 
   endpoint:
    health:
     show-details: always	   
   health:
    circuitbreakers:
      enabled: true
   tracing:
     sampling:
       probability: 1.0
   zipkin:
    tracing:
     endpoint: ${ZIPKIN_URL:http://zipkin:9411/api/v2/spans}
     connect-timeout: 1s
     encoding: json 
     read-timeout: 10s