spring:

#RabbitMq-Connection
# rabbitmq:
#   host: localhost
#   port: 5672
#   username: guest
#   password: guest

#Cloud-Stream-Bindings
 cloud:

#Cloud-Stream-Bindings-RabbitMq-Kafka
  function:
    definition: orderCreated
  stream:
    function:
       definition: orderCreated
    bindings:
      orderCreated-in-0:
        destination: order.exchange
        group: notification-group 
        content-type: application/json

#Cloud-Stream-Bindings-Kafka

    kafka:
     binder:
      brokers: localhost:9092

server:
 port: 8095
 
logging:
 level:
  root: INFO
 file:
  name: logs/${spring.application.name}.log
 logback:
   rollingpolicy:
     max-file-size: 5MB
     max-history: 1

#RabbitMQ

#rabbitmq:
#  exchange:
#    name: order.exchange
#  queue:
#    name: order.queue
#  routing:
#    key: order.tracking
